// File generated by FlutterFire CLI.
// PLACEHOLDER — replace this whole file by running:
//   flutterfire configure
// from the project root once the Firebase project exists. That command
// overwrites this file with your project's real platform configs.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run `flutterfire configure`.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform — '
          'run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOosqe5tmoU_ddItUnmEtbxp4WVpLTle4',
    appId: '1:649750627241:android:c57a12ca2b1349ee343ab8',
    messagingSenderId: '649750627241',
    projectId: 'foodsnap-app-74616',
    storageBucket: 'foodsnap-app-74616.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy1rVrrM4Dvnzd4rPTOPuzEhjspTKBT2o',
    appId: '1:649750627241:ios:102ecfd55e8bf226343ab8',
    messagingSenderId: '649750627241',
    projectId: 'foodsnap-app-74616',
    storageBucket: 'foodsnap-app-74616.firebasestorage.app',
    iosBundleId: 'com.dctooandy.foodsnap',
  );
}
